#!/bin/bash
# Regenerate the .bat and .sh scripts that are generated by build.xml. Used by Renovate as post-upgrade
# task (see renovate.json) after it has updated download versions in build.xml.
# env.sh is sourced instead of executed because build.xml can regenerate env.sh while it is running (bash
# reads a sourced file completely before executing it, while an executed script is read while running).
cd "$(dirname "${BASH_SOURCE[0]}")/../.."
source ./env.sh
"${ANT_HOME}/bin/ant" -emacs -buildfile build.xml init generate.scripts
