name: Linux test
on:
  push:
  pull_request:

jobs:
  testing:
    name: Linux test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache Frank!Runner dependencies - build
      uses: actions/cache@v2
      with:
        path: build
        key: ${{ runner.os }}-frank-runner-build
        restore-keys: ${{ runner.os }}-frank-runner-build
    - name: Cache Frank!Runner dependencies - download
      uses: actions/cache@v2
      with:
        path: download
        key: ${{ runner.os }}-frank-runner-download
        restore-keys: ${{ runner.os }}-frank-runner-download
    - name: Cache Maven downloads
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/
        key: ${{ runner.os }}-maven
        restore-keys: ${{ runner.os }}-maven

    - name: Start Frank!Runner
      run: ./start.sh > startup.log &
    - name: Wait for website localhost
      uses: nev7n/wait_for_response@v1
      with:
        url: 'http://localhost'
        timeout: 5000
        interval: 150000

    - name: Save startup log
      uses: actions/upload-artifact@v2
      if: always()
      with:
        path: startup.log
